Adding few sites
Draluy/cookienotificationhider pull request #2
Opened 2019-05-05 18:12 UTC by Lisapple

With some refactoring for Quantcast.

2019-05-05 21:57 UTC, Draluy requested changes

2019-05-05 21:57 UTC, Draluy commented on hiders/HiderRepository.js
> +    ".bottom.cookie-bar.cookie-gdpr"
Il manque du code autour de ce selecteur.

2019-05-05 22:33 UTC, Lisapple commented on hiders/HiderRepository.js
> +    ".bottom.cookie-bar.cookie-gdpr"
Yep désolé, c'est corrigé

2019-05-06 17:36 UTC, Draluy approved these changes
Joli travail, merci :)

2019-05-06 17:37 UTC, merged